# netlify.toml

[build]
  # This command builds your React app for production
  command = "npm run build"

  # This is the folder where the build output is placed (usually "dist" or "build")
  publish = "dist"

  # This tells Netlify where to find your serverless functions
  functions = "netlify/functions/"

# This rule is important for Single-Page Apps like React
# It ensures that all paths are handled by your index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200