[build]
  command   = "npm run build"
  publish   = "build"         # or "dist" if you’re using Vite

[functions]
  directory = "netlify/functions"

[[redirects]]
  # Proxy function calls first
  from    = "/.netlify/functions/*"
  to      = "/.netlify/functions/:splat"
  status  = 200

[[redirects]]
  # Then catch-all for your SPA
  from    = "/*"
  to      = "/index.html"
  status  = 200
